### PR TITLE
Added Asset type and a call to it

### PR DESCRIPTION
**Pull request by SlavaTT**

### CODE REVIEW

**Comment by alokym86** [comment]
@SlavaTT since IBitmexNonTradeFeaturesClient/BitmexNonTradeFeatureClient contain methods that aren't connected to trading at all, I propose to move GetWalletAssetsAsync() method to BitmexBaseTradeClient/IBitmexCommonTradeClient class/interface. Do you agree?

**Comment by SlavaTT** [comment]
Yes, agree. Will you release new nuget package version ?

**Comment by alokym86** [comment]
@SlavaTT not me. But yep, I'd already made a pull request with this change.

**Comment by ridicoulous** [comment]
v 2.0.0 was released

**Comment by SlavaTT** [comment]
Thank you. Quickly skachivayu!!.

**Pull request merged**
